# Sonata Admin Search Bundle
# Configuration: https://sonata-project.org/bundles/admin-search/master/doc/reference/configuration.html
sonata_admin_search:
    admin_finder_services:
#        sonata.news.admin.post: # Admin service id
#            finder: Id for a FOS finder service that should be used # Finder service
#            actions : [list] #[Optional] actions where elasticsearch has to be enabled
